name: Sky-Block Wars
main: me.kyle.burnett.SkyBlockWarriors.Main
version: 1.0.0
author: Burnett
description: >
             Sky block warrior plugin.
commands:
    skyblockw:
        description: Main command.
        aliases: [sw]
        usage: /<command> arguments
permissions:
    skyblockwars.admin:
        children:
            skyblockwars.builder: true
            skyblockwars.usecommands: true
            skyblockwars.setlobby: true
            skyblockwars.enable: true
            skyblockwars.disable: true
            skyblockwars.activate: true
            skyblockwars.deactivate: true
            skyblockwars.save: true
            skyblockwars.load: true
            skyblockwars.reload: true
            skyblockwars.help.admin: true
            skyblockwars.prepare: true
            skyblockwars.endgame: true
            skyblockwars.updatesigns: true
        default: op
    skyblockwars.builder:
        children:
            skyblockwars.create: true
            skyblockwars.create.override: true
            skyblockwars.confirm: true
            skyblockwars.edit: true
            skyblockwars.setspawn: true
            skyblockwars.addchest: true
            skyblockwars.user: true
            skyblockwars.help.builder: true
            skyblockwars.sign.create: true
        default: op
    skyblockwars.user:
        children:
            skyblockwars.join: true
            skyblockwars.list: true
            skyblockwars.listgames: true
            skyblockwars.team: true
            skyblockwars.vote: true
            skyblockwars.sign.join: true
            skyblockwars.sign.leave: true
            skyblockwars.leader: true
            skyblockwars.stats: true
            skyblockwars.spectate: true
    skyblockwars.info:
        default: op
    skyblockwars.join:
        default: op
    skyblockwars.list:
        default: op
    skyblockwars.listgames:
        default: op
    skyblockwars.team:
        default: op
    skyblockwars.vote:
        default: op
    skyblockwars.create:
        default: op
    skyblockwars.create.override:
        default: op
    skyblockwars.confirm:
        default: op
    skyblockwars.edit:
        default: op
    skyblockwars.setspawn:
        default: op
    skyblockwars.addchest:
        default: op
    skyblockwars.usecommands:
        default: op
    skyblockwars.setlobby:
        default: op
    skyblockwars.enable:
        default: op
    skyblockwars.disable:
        default: op
    skyblockwars.activate:
        default: op
    skyblockwars.deactivate:
        default: op
    skyblockwars.save:
        default: op
    skyblockwars.load:
        default: op
    skyblockwars.reload:
        default: op
    skyblockwars.help.builder:
        default: op
    skyblockwars.help.admin:
        default: op
    skyblockwars.prepare:
        default: op
    skyblockwars.sign.join:
        default: op
    skyblockwars.sign.leave:
        default: op
    skyblockwars.sign.create:
        default: op
    skyblockwars.leader:
        default: op
    skyblockwars.stats:
        default: op
    skyblockwars.endgame:
        default: op
    skyblockwars.spectate:
        default: op
    skyblockwars.info:
        default: op
    skyblockwars.updatesigns:
        default: op
